apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1

  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api

    spec:
      containers:
        - name: api
          image: sameusers/api:2483a1dd5478a77161f96d91d21df41bef6045e5

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets

          env:
            - name: PORT
              value: "8000"

          imagePullPolicy: Always

          resources:
            requests:
              cpu: "248m"
              memory: "64Mi"

            limits:
              cpu: "512m"
              memory: "128Mi"
