apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2

  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api

    spec:
      containers:
        - name: api
          image: sameusers/api:629801c6fb81f44032c4f59645d22506272ed77b

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets

          env:
            - name: PORT
              value: "8000"

          imagePullPolicy: Always